### ISSUE TITLE
Have to go into Mod Settings and press OK in the Rumble Mod settings every time in start beat saber

### ISSUE THREAD

**Issue by Vogeluff** [nalulululuna/RumbleMod#3]
yeah basically what the title says. cool mod, it helped me to make the rumble feel more like pre-multiplayer patch and not so super weak like it does since but i have to go into the settings of the rumble mod every time i start beat saber. even though if i go there my settings are already put in and i only press ok that makes it work, otherwise it will choose your preset (i think?). or its the games preset but i think its yours. not sure actually.

**Comment by nalulululuna** [comment]
I'm sorry for the late reply. This bug has already been fixed in the current version.
