### ISSUE TITLE
rumble goes off 

### ISSUE THREAD

**Issue by tu0mas** [nalulululuna/RumbleMod#4]
It randomly stops rumbling mid song then it rumbles again, I'm on valve index.

**Comment by Vogeluff** [comment]
i had something similar if i for example missed a note and there were too many notes it felt like it couldnt keep up and there were gaps inbetween the rumble but not sure if you mean that

**Comment by Vinjul1704** [comment]
I experience the same issue with my vive.

**Comment by nalulululuna** [comment]
The original rumble code in Beat Saber simply generates a brief vibration when the notes are cut. And my mod just changes the parameters of that vibration. This means that the situation you experienced is probably caused at the driver level, and is difficult to fix by either Beat Saber official or me.

**Comment by Vinjul1704** [comment]
Makes sense, thanks! I readjusted my base stations a week ago and that seemed to have fixed it. I just got an index 2 days ago and it doesn't seem to have that issue either.

**Comment by tu0mas** [comment]
Yep. I've figured out the problem didn't come from the mod but from the game itself. Anyway it's fixed on my end, thanks to HardCPP. Great mod by the way!

**Comment by Vinjul1704** [comment]
I agree it's a great mod. Makes the game only really playable for me. Just wish it can be installed from mod managers directly.
