### ISSUE TITLE
no installation guide

### ISSUE THREAD

**Issue by niratis** [nalulululuna/RumbleMod#5]
Hey there,

thanks for the mod! Could you help with an installation guide on this, I want to have this on my Oculus Quest 2, but even after using google for a while I was unable to figure out what to do : /

**Comment by nalulululuna** [comment]
Sorry, this mod is for PC only. If you are using the Steam version of BeatSaber on PC, here are the instructions
1. Install BS Utils and BeatSaberMarkupLanguage via ModAssistant
　(If your mod environment is already set up, it's probably already in there.)
2. Move the downloaded dll file to the following location*
　C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Plugins
* The above description is for the default installation of Beat Saber for Steam.
   If your installation location is different, please change the description accordingly.
